version: '3'
services:
  database:
    container_name: mongodb
    image: 'mongodb:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    container_name: nodejs
    build: ./server
  frontend:
    container_name: reactjs
    build: ./client
