version: '3'
services:
  database:
    container_name: mongodb
    image: 'mongo:latest'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nimda
      MONGO_INITDB_ROOT_PASSWORD: nimda
  database-ui:
    container_name: mongoadmin
    image: 'mongo-express:latest'
    depends_on:
      - "database"
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER="mongodb"
      - ME_CONFIG_MONGODB_ADMINUSERNAME="nimda"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="nimda"
  server-api:
    container_name: nodejs
    build: ./server
    ports:
      - "3100:3100"
    environment: 
      - MONGODB_CONNSTRING=mongodb://nimda:nimda@mongodb
  client-ui:
    container_name: nextjs
    build: ./client
    ports:
      - "3000:3000"
