# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
commands:
  build:
    steps:
      - checkout
executors:
  circleci-docker:
    docker:
      - image: cimg/node:16.13
    working_directory: ~/project
jobs:
  test-server-api:
    executor: circleci-docker
    steps:
      - build
      - run:
          name: Unit Tests
          command: |
            cd server
            npm i
            npm test
  test-client-ui:
    executor: circleci-docker
    steps:
      - build
      - run:
          name: Unit Tests
          command: npm test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-server-api
      - test-client-ui
