# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  test-server-api:
    docker:
      - image: jaebea/task-manager-momo:server-api
    working_directory: ~/server
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: echo "Jest comming soon!"
  test-client-ui:
    docker:
      - image: jaebea/task-manager-momo:client-ui
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: echo "Jest comming soon!"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-server-api
      - test-client-ui