import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

import TextInput from '../components/TextInput/TextInput'

export default function Home() {
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();

  const fieldUsername = {
    id: 'username',
    label: 'Username'
  }

  const fieldPassword = {
    id: 'password',
    label: 'Password'
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form>
          <TextInput {...fieldUsername} />
          <TextInput {...fieldPassword} />
          
          <label htmlFor="username">Username</label>
          <input type="text" value={username} onChange={(e) => (e.target.value)} />
          <label htmlFor="password">Password</label>
          <input type="text" value={password} onChange={(e) => (e.target.value)} />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
